admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

api:
    resource: "@ApiBundle/Controller/V1"
    prefix:   /api/v1
    type:     annotation

games:
    resource: "@GamesBundle/Resources/config/routing.yml"
    prefix:   /games

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /apidoc
